### ISSUE TITLE
Réalisation de fiches/cas de tests

### ISSUE THREAD

**Issue by Drainman** [Hagbuck/poly-compiler#1]
A préparer avec le rendu et pour nous tout simplement, préparer quelques scénarios et cas de tests (ex : priorités opératoires, caractères invalides etc...) 
Editer pour idées : 

- 3 * 4 + 9 * 2
- 4 + (6 * 3

**Comment by Hagbuck** [comment]
`3 - ` doit soulever une erreur avant le *code_gen*

Corrigé depuis le dernier commit : eaf7d7f

**Comment by Drainman** [comment]
L'entrée  `5 1 3` doit lever une erreur de compilation.
Pour le moment génère : 

```
[node_const] ~ 5 ~ (1;0) ~ 0 child(s)
[RESULT] -> 5
```

Corrigé depuis le dernier commit : eaf7d7f

**Comment by Drainman** [comment]
Bugs signalés plus haut corrigés depuis la eaf7d7f.

**Comment by Hagbuck** [comment]
L'utilisation d'une variable sans déclaration : 

```
var x;
x = 1;
z = x;
```

Génère l'erreur semantique : `[ERROR] ~ Error : z is not defined`

**Comment by Hagbuck** [comment]
La double déclaration d'une même variable : 

```
var x;
var x;
y = x - 3;
```

Génère l'erreur semantique : `[ERROR] ~ Error : x is already defined`

**Comment by Hagbuck** [comment]
```
p1(x){
    return x + 1;
}

main(){
    var a;
    var b;
    
    a = p1(b) = 7;
    
    print a;
    print b;
}
```

Doit lever une erreur car on affecte une constante à une constance. On doit vérifier lors du **node** affectation que le premier fils est un bien un **varRef**

**EDIT :** DONE, code ajouté dans la fonction semantic_analyze. Ce code génère bien une erreur de compilation

**Comment by Hagbuck** [comment]
```
p1(x){
    return x + 1;
}

main(){
    var a;
    
    a = 0;
    
    while( a < 5 ){
        a = p1(a);
        print a;
    }
}
```

Affiche : 
```
1
```
